### ISSUE TITLE
QPython310 is not loaded before qBittorrent

### ISSUE THREAD

**Issue by ittayd** [OneCDOnly/SortMyQPKGs#14]
QPython310 is in the alpha list, but when I run `sudo /etc/init.d/sortmyqpkgs.sh fix`, the new order is:
(01) (A) netmgr
(02) (A) QJDK17
(03) (A) Apache80
(04) (A) MultimediaConsole
(05) (A) PlexMediaServer
(06) (A) HybridBackup
(07) (Φ) LicenseCenter
(08) (Φ) NotificationCenter
(09) (Φ) QuLog
(10) (Φ) ResourceMonitor
(11) (Φ) helpdesk
(12) (Φ) CloudLink
(13) (Φ) QDMS
(14) (Φ) QcloudSSLCertificate
(15) (Φ) Qboost
(16) (Φ) qBittorrent
(17) (Φ) RadarrDotNet80
(18) (Φ) JackettdotNET80
(19) (Φ) QPython310
(20) (Φ) Prowlarr80
(21) (Φ) SecurityCounselor
(22) (Φ) qufirewall
(23) (Φ) QDK
(24) (Ω) QBazarr
(25) (Ω) MalwareRemover
(26) (Ω) SortMyQPKGs

**Comment by ittayd** [comment]
So it seems in my machine, the ALPHA.default file doesn't contain QPython310. But I installed today and the package is from 17/3. 
(Suggestion: maybe support package pattern names, e.g. QPython* or Apache* such that new variants will be sorted without the need to update the alpha/omega lists)

**Comment by ittayd** [comment]
I see there is a way to write an ALPHA.custom file, the thing is, once it is there, it overrides all of the ALPHA.default contents. Maybe support ALPHA.add (and maybe ALPHA.remove) so I can just add QPython310?

**Comment by OneCDOnly** [comment]
You'll need to use the latest version of SortMyQPKGs. It's not available on QNAPClub. 

You can download it from this repo, or else install the sherpa package manager, then use it to upgrade your SortMyQPKGs.

**Comment by OneCDOnly** [comment]
If you’re using SortMyQPKGs from the QNAPClub, you’ll find it doesn’t
include the latest version of SortMyQPKGs (which has QPython310 in the
ALPHA list).

To get the most recent SortMyQPKGs, you can either manually download it
from GitHub, or else install the sherpa package manager.
