### ISSUE TITLE
Qtransmission should be before NGiNX

### ISSUE THREAD

**Issue by atais** [OneCDOnly/SortMyQPKGs#15]
Hello

I am using NGiNX to proxy to QTransmission webui.
And for some reason if it is in the current order:

```
...
(15) (Φ) NGinX
(21) (Ω) QTransmission
```

I need to restart QTransmission for WebUI to be avaialble through proxy.
Would the startup order fix that issue?

Thanks

**Comment by OneCDOnly** [comment]
Hey @atais :)

Hmm, it's odd that a restart of QTransmission fixes this. It already loads after NGIИX. 

BTW: where did your NGIИX package come from? The Qnapclub version should be spelt "Nginx". Yours is spelt "NGinX"

I can't say for sure that rearranging the startup order will fix this (as it's already correct), but if you could try this and let me know how it goes, I'd appreciate it.

**Comment by atais** [comment]
I am using https://www.qnapclub.eu/pl/qpkg/642

It (supposedly) is newer than https://www.qnapclub.eu/pl/qpkg/198 (1.21 vs 1.12)

**Comment by OneCDOnly** [comment]
Ah, thank you. I'll include that new package name in the next version of SortMyQPKGs. Not sure when it will be released though. 

In the meantime, can you let me know if you find a solution to your issue? Does changing the package order in your local copy of SortMyQPKGs make it work?

**Comment by atais** [comment]
I reboot rarely so I manually restart qTransmission after that 😄 
Thought maybe you'd have an idea what's wrong.

**Comment by OneCDOnly** [comment]
Sorry, no: I don't know why this happens. You could try asking @QNAP_Stephane on the [QNAP Community Forum](https://forum.qnap.com/index.php) about this, as these are his QPKGs.

**Comment by OneCDOnly** [comment]
@atais any progress here? Can we close this issue?
