### ISSUE TITLE
Qnapclub down

### ISSUE THREAD

**Issue by amau05** [OneCDOnly/SortMyQPKGs#16]
Hi it's impossible to add install your qpkg as the qnapclub is down since several days.

**Comment by OneCDOnly** [comment]
Hi @amau05 , thanks for the reminder. 👍🏽 

I've just emailed the [myqnap.org](https://myqnap.org) repository with a small collection of QPKGs (including SortMyQPKGs) so these can be added to that repo. It may take a few days (or not) for these packages to be processed. I'll post back here when I've confirmed they're available.

**Comment by amau05** [comment]
Your apps are available on Myqnap so I close this topic.
