### ISSUE TITLE
OMEGA.default lacks qBittorrent 

### ISSUE THREAD

**Issue by Mojelly** [OneCDOnly/SortMyQPKGs#17]
OMEGA.default lacks qBittorrent (letter case sensitivity), which prevents qBittorrent from being sorted correctly and starts after QPython3xx. 
After manually adding qBittorrent, it will be sorted normally. Please add qBittorrent in OMEGA.default in subsequent updates. Thank you!

**Comment by OneCDOnly** [comment]
Will do. Thanks for reporting this. 

Cheers!

**Comment by OneCDOnly** [comment]
Just a follow-up question for you: which QPython3xx QPKG version is installed? (as-in: what is the xx?)

**Comment by Mojelly** [comment]
> Just a follow-up question for you: which QPython3xx QPKG version is installed? (as-in: what is the xx?)

just like QPython39, 310, 311

**Comment by OneCDOnly** [comment]
Thanks mate. 👍

It will be included in the next release.
