### ISSUE TITLE
ERROR: SortMyQPKGs (20180320) [Sun Apr  1 15:49:30 PDT 2018] 'install' requested

### ISSUE THREAD

**Issue by ltjdym** [OneCDOnly/SortMyQPKGs#6]
I'm getting this error when I open the app in QNAP? Any tips? Newest OS.

SortMyQPKGs (20180320)
[Sun Apr  1 15:49:30 PDT 2018] 'install' requested

**Comment by OneCDOnly** [comment]
Hi @ltjdym. 

This is normal when you've just installed the app and is not an error.

The open button just displays the log of previous sort operations. When the app has just been installed, the log is empty, so I included an 'install' message so that the user would see something.
